version: "3"

services:
  mysql:
    image: mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookrenting
      MYSQL_USER: bookrenting
      MYSQL_PASSWORD: bookrenting
